from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.common_response_status import CommonResponseStatus
from backend.utils import util

from backend.models.common_response_status import CommonResponseStatus  # noqa: E501

class AuthChallengeResponseBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, result=None):  # noqa: E501
        """AuthChallengeResponseBody - a model defined in OpenAPI

        :param status: The status of this AuthChallengeResponseBody.  # noqa: E501
        :type status: CommonResponseStatus
        :param result: The result of this AuthChallengeResponseBody.  # noqa: E501
        :type result: str
        """
        self.openapi_types = {
            'status': CommonResponseStatus,
            'result': str
        }

        self.attribute_map = {
            'status': 'status',
            'result': 'result'
        }

        self._status = status
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'AuthChallengeResponseBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authChallengeResponseBody of this AuthChallengeResponseBody.  # noqa: E501
        :rtype: AuthChallengeResponseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> CommonResponseStatus:
        """Gets the status of this AuthChallengeResponseBody.


        :return: The status of this AuthChallengeResponseBody.
        :rtype: CommonResponseStatus
        """
        return self._status

    @status.setter
    def status(self, status: CommonResponseStatus):
        """Sets the status of this AuthChallengeResponseBody.


        :param status: The status of this AuthChallengeResponseBody.
        :type status: CommonResponseStatus
        """

        self._status = status

    @property
    def result(self) -> str:
        """Gets the result of this AuthChallengeResponseBody.


        :return: The result of this AuthChallengeResponseBody.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this AuthChallengeResponseBody.


        :param result: The result of this AuthChallengeResponseBody.
        :type result: str
        """

        self._result = result
