from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.common_response_status import CommonResponseStatus
from backend.utils import util

from backend.models.common_response_status import CommonResponseStatus  # noqa: E501

class AuthVerifyResponseBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, token=None):  # noqa: E501
        """AuthVerifyResponseBody - a model defined in OpenAPI

        :param status: The status of this AuthVerifyResponseBody.  # noqa: E501
        :type status: CommonResponseStatus
        :param token: The token of this AuthVerifyResponseBody.  # noqa: E501
        :type token: str
        """
        self.openapi_types = {
            'status': CommonResponseStatus,
            'token': str
        }

        self.attribute_map = {
            'status': 'status',
            'token': 'token'
        }

        self._status = status
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'AuthVerifyResponseBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authVerifyResponseBody of this AuthVerifyResponseBody.  # noqa: E501
        :rtype: AuthVerifyResponseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> CommonResponseStatus:
        """Gets the status of this AuthVerifyResponseBody.


        :return: The status of this AuthVerifyResponseBody.
        :rtype: CommonResponseStatus
        """
        return self._status

    @status.setter
    def status(self, status: CommonResponseStatus):
        """Sets the status of this AuthVerifyResponseBody.


        :param status: The status of this AuthVerifyResponseBody.
        :type status: CommonResponseStatus
        """

        self._status = status

    @property
    def token(self) -> str:
        """Gets the token of this AuthVerifyResponseBody.


        :return: The token of this AuthVerifyResponseBody.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this AuthVerifyResponseBody.


        :param token: The token of this AuthVerifyResponseBody.
        :type token: str
        """

        self._token = token
