from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.auth_verify_response_body import AuthVerifyResponseBody
from backend.models.common_message_header import CommonMessageHeader
from backend.utils import util

from backend.models.auth_verify_response_body import AuthVerifyResponseBody  # noqa: E501
from backend.models.common_message_header import CommonMessageHeader  # noqa: E501

class AuthVerifyResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, header=None, body=None):  # noqa: E501
        """AuthVerifyResponse - a model defined in OpenAPI

        :param header: The header of this AuthVerifyResponse.  # noqa: E501
        :type header: CommonMessageHeader
        :param body: The body of this AuthVerifyResponse.  # noqa: E501
        :type body: AuthVerifyResponseBody
        """
        self.openapi_types = {
            'header': CommonMessageHeader,
            'body': AuthVerifyResponseBody
        }

        self.attribute_map = {
            'header': 'header',
            'body': 'body'
        }

        self._header = header
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'AuthVerifyResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authVerifyResponse of this AuthVerifyResponse.  # noqa: E501
        :rtype: AuthVerifyResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def header(self) -> CommonMessageHeader:
        """Gets the header of this AuthVerifyResponse.


        :return: The header of this AuthVerifyResponse.
        :rtype: CommonMessageHeader
        """
        return self._header

    @header.setter
    def header(self, header: CommonMessageHeader):
        """Sets the header of this AuthVerifyResponse.


        :param header: The header of this AuthVerifyResponse.
        :type header: CommonMessageHeader
        """

        self._header = header

    @property
    def body(self) -> AuthVerifyResponseBody:
        """Gets the body of this AuthVerifyResponse.


        :return: The body of this AuthVerifyResponse.
        :rtype: AuthVerifyResponseBody
        """
        return self._body

    @body.setter
    def body(self, body: AuthVerifyResponseBody):
        """Sets the body of this AuthVerifyResponse.


        :param body: The body of this AuthVerifyResponse.
        :type body: AuthVerifyResponseBody
        """

        self._body = body
