from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.auth_verify_request_body import AuthVerifyRequestBody
from backend.models.common_message_header import CommonMessageHeader
from backend.utils import util

from backend.models.auth_verify_request_body import AuthVerifyRequestBody  # noqa: E501
from backend.models.common_message_header import CommonMessageHeader  # noqa: E501

class AuthVerifyRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, header=None, body=None):  # noqa: E501
        """AuthVerifyRequest - a model defined in OpenAPI

        :param header: The header of this AuthVerifyRequest.  # noqa: E501
        :type header: CommonMessageHeader
        :param body: The body of this AuthVerifyRequest.  # noqa: E501
        :type body: AuthVerifyRequestBody
        """
        self.openapi_types = {
            'header': CommonMessageHeader,
            'body': AuthVerifyRequestBody
        }

        self.attribute_map = {
            'header': 'header',
            'body': 'body'
        }

        self._header = header
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'AuthVerifyRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authVerifyRequest of this AuthVerifyRequest.  # noqa: E501
        :rtype: AuthVerifyRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def header(self) -> CommonMessageHeader:
        """Gets the header of this AuthVerifyRequest.


        :return: The header of this AuthVerifyRequest.
        :rtype: CommonMessageHeader
        """
        return self._header

    @header.setter
    def header(self, header: CommonMessageHeader):
        """Sets the header of this AuthVerifyRequest.


        :param header: The header of this AuthVerifyRequest.
        :type header: CommonMessageHeader
        """

        self._header = header

    @property
    def body(self) -> AuthVerifyRequestBody:
        """Gets the body of this AuthVerifyRequest.


        :return: The body of this AuthVerifyRequest.
        :rtype: AuthVerifyRequestBody
        """
        return self._body

    @body.setter
    def body(self, body: AuthVerifyRequestBody):
        """Sets the body of this AuthVerifyRequest.


        :param body: The body of this AuthVerifyRequest.
        :type body: AuthVerifyRequestBody
        """

        self._body = body
