from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.utils import util


class AuthChallengeRequestRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address=None):  # noqa: E501
        """AuthChallengeRequestRequestBody - a model defined in OpenAPI

        :param address: The address of this AuthChallengeRequestRequestBody.  # noqa: E501
        :type address: str
        """
        self.openapi_types = {
            'address': str
        }

        self.attribute_map = {
            'address': 'address'
        }

        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'AuthChallengeRequestRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authChallengeRequestRequestBody of this AuthChallengeRequestRequestBody.  # noqa: E501
        :rtype: AuthChallengeRequestRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> str:
        """Gets the address of this AuthChallengeRequestRequestBody.


        :return: The address of this AuthChallengeRequestRequestBody.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this AuthChallengeRequestRequestBody.


        :param address: The address of this AuthChallengeRequestRequestBody.
        :type address: str
        """

        self._address = address
