from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.auth_challenge_request_request_body import AuthChallengeRequestRequestBody
from backend.models.common_message_header import CommonMessageHeader
from backend.utils import util

from backend.models.auth_challenge_request_request_body import AuthChallengeRequestRequestBody  # noqa: E501
from backend.models.common_message_header import CommonMessageHeader  # noqa: E501

class AuthChallengeRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, header=None, body=None):  # noqa: E501
        """AuthChallengeRequest - a model defined in OpenAPI

        :param header: The header of this AuthChallengeRequest.  # noqa: E501
        :type header: CommonMessageHeader
        :param body: The body of this AuthChallengeRequest.  # noqa: E501
        :type body: AuthChallengeRequestRequestBody
        """
        self.openapi_types = {
            'header': CommonMessageHeader,
            'body': AuthChallengeRequestRequestBody
        }

        self.attribute_map = {
            'header': 'header',
            'body': 'body'
        }

        self._header = header
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'AuthChallengeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authChallengeRequest of this AuthChallengeRequest.  # noqa: E501
        :rtype: AuthChallengeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def header(self) -> CommonMessageHeader:
        """Gets the header of this AuthChallengeRequest.


        :return: The header of this AuthChallengeRequest.
        :rtype: CommonMessageHeader
        """
        return self._header

    @header.setter
    def header(self, header: CommonMessageHeader):
        """Sets the header of this AuthChallengeRequest.


        :param header: The header of this AuthChallengeRequest.
        :type header: CommonMessageHeader
        """

        self._header = header

    @property
    def body(self) -> AuthChallengeRequestRequestBody:
        """Gets the body of this AuthChallengeRequest.


        :return: The body of this AuthChallengeRequest.
        :rtype: AuthChallengeRequestRequestBody
        """
        return self._body

    @body.setter
    def body(self, body: AuthChallengeRequestRequestBody):
        """Sets the body of this AuthChallengeRequest.


        :param body: The body of this AuthChallengeRequest.
        :type body: AuthChallengeRequestRequestBody
        """

        self._body = body
