from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.utils import util


class AuthVerifyRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address=None, signature=None):  # noqa: E501
        """AuthVerifyRequestBody - a model defined in OpenAPI

        :param address: The address of this AuthVerifyRequestBody.  # noqa: E501
        :type address: str
        :param signature: The signature of this AuthVerifyRequestBody.  # noqa: E501
        :type signature: str
        """
        self.openapi_types = {
            'address': str,
            'signature': str
        }

        self.attribute_map = {
            'address': 'address',
            'signature': 'signature'
        }

        self._address = address
        self._signature = signature

    @classmethod
    def from_dict(cls, dikt) -> 'AuthVerifyRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authVerifyRequestBody of this AuthVerifyRequestBody.  # noqa: E501
        :rtype: AuthVerifyRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> str:
        """Gets the address of this AuthVerifyRequestBody.


        :return: The address of this AuthVerifyRequestBody.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this AuthVerifyRequestBody.


        :param address: The address of this AuthVerifyRequestBody.
        :type address: str
        """

        self._address = address

    @property
    def signature(self) -> str:
        """Gets the signature of this AuthVerifyRequestBody.


        :return: The signature of this AuthVerifyRequestBody.
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature: str):
        """Sets the signature of this AuthVerifyRequestBody.


        :param signature: The signature of this AuthVerifyRequestBody.
        :type signature: str
        """

        self._signature = signature
