from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.auth_challenge_response_body import AuthChallengeResponseBody
from backend.models.common_message_header import CommonMessageHeader
from backend.utils import util

from backend.models.auth_challenge_response_body import AuthChallengeResponseBody  # noqa: E501
from backend.models.common_message_header import CommonMessageHeader  # noqa: E501

class AuthChallengeResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, header=None, body=None):  # noqa: E501
        """AuthChallengeResponse - a model defined in OpenAPI

        :param header: The header of this AuthChallengeResponse.  # noqa: E501
        :type header: CommonMessageHeader
        :param body: The body of this AuthChallengeResponse.  # noqa: E501
        :type body: AuthChallengeResponseBody
        """
        self.openapi_types = {
            'header': CommonMessageHeader,
            'body': AuthChallengeResponseBody
        }

        self.attribute_map = {
            'header': 'header',
            'body': 'body'
        }

        self._header = header
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'AuthChallengeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authChallengeResponse of this AuthChallengeResponse.  # noqa: E501
        :rtype: AuthChallengeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def header(self) -> CommonMessageHeader:
        """Gets the header of this AuthChallengeResponse.


        :return: The header of this AuthChallengeResponse.
        :rtype: CommonMessageHeader
        """
        return self._header

    @header.setter
    def header(self, header: CommonMessageHeader):
        """Sets the header of this AuthChallengeResponse.


        :param header: The header of this AuthChallengeResponse.
        :type header: CommonMessageHeader
        """

        self._header = header

    @property
    def body(self) -> AuthChallengeResponseBody:
        """Gets the body of this AuthChallengeResponse.


        :return: The body of this AuthChallengeResponse.
        :rtype: AuthChallengeResponseBody
        """
        return self._body

    @body.setter
    def body(self, body: AuthChallengeResponseBody):
        """Sets the body of this AuthChallengeResponse.


        :param body: The body of this AuthChallengeResponse.
        :type body: AuthChallengeResponseBody
        """

        self._body = body
