from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.common_authenticate_type_enum import CommonAuthenticateTypeEnum
from backend.utils import util

from backend.models.common_authenticate_type_enum import CommonAuthenticateTypeEnum  # noqa: E501

class CommonMessageHeader(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, did=None, auth_type=CommonAuthenticateTypeEnum.AUTHENTICATE_TYPE_UNKNOWN, auth_content=None, nonce=None, timestamp=None, version=None):  # noqa: E501
        """CommonMessageHeader - a model defined in OpenAPI

        :param did: The did of this CommonMessageHeader.  # noqa: E501
        :type did: str
        :param auth_type: The auth_type of this CommonMessageHeader.  # noqa: E501
        :type auth_type: CommonAuthenticateTypeEnum
        :param auth_content: The auth_content of this CommonMessageHeader.  # noqa: E501
        :type auth_content: str
        :param nonce: The nonce of this CommonMessageHeader.  # noqa: E501
        :type nonce: str
        :param timestamp: The timestamp of this CommonMessageHeader.  # noqa: E501
        :type timestamp: str
        :param version: The version of this CommonMessageHeader.  # noqa: E501
        :type version: int
        """
        self.openapi_types = {
            'did': str,
            'auth_type': CommonAuthenticateTypeEnum,
            'auth_content': str,
            'nonce': str,
            'timestamp': str,
            'version': int
        }

        self.attribute_map = {
            'did': 'did',
            'auth_type': 'authType',
            'auth_content': 'authContent',
            'nonce': 'nonce',
            'timestamp': 'timestamp',
            'version': 'version'
        }

        self._did = did
        self._auth_type = auth_type
        self._auth_content = auth_content
        self._nonce = nonce
        self._timestamp = timestamp
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'CommonMessageHeader':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The commonMessageHeader of this CommonMessageHeader.  # noqa: E501
        :rtype: CommonMessageHeader
        """
        return util.deserialize_model(dikt, cls)

    @property
    def did(self) -> str:
        """Gets the did of this CommonMessageHeader.


        :return: The did of this CommonMessageHeader.
        :rtype: str
        """
        return self._did

    @did.setter
    def did(self, did: str):
        """Sets the did of this CommonMessageHeader.


        :param did: The did of this CommonMessageHeader.
        :type did: str
        """

        self._did = did

    @property
    def auth_type(self) -> CommonAuthenticateTypeEnum:
        """Gets the auth_type of this CommonMessageHeader.


        :return: The auth_type of this CommonMessageHeader.
        :rtype: CommonAuthenticateTypeEnum
        """
        return self._auth_type

    @auth_type.setter
    def auth_type(self, auth_type: CommonAuthenticateTypeEnum):
        """Sets the auth_type of this CommonMessageHeader.


        :param auth_type: The auth_type of this CommonMessageHeader.
        :type auth_type: CommonAuthenticateTypeEnum
        """

        self._auth_type = auth_type

    @property
    def auth_content(self) -> str:
        """Gets the auth_content of this CommonMessageHeader.


        :return: The auth_content of this CommonMessageHeader.
        :rtype: str
        """
        return self._auth_content

    @auth_content.setter
    def auth_content(self, auth_content: str):
        """Sets the auth_content of this CommonMessageHeader.


        :param auth_content: The auth_content of this CommonMessageHeader.
        :type auth_content: str
        """

        self._auth_content = auth_content

    @property
    def nonce(self) -> str:
        """Gets the nonce of this CommonMessageHeader.


        :return: The nonce of this CommonMessageHeader.
        :rtype: str
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce: str):
        """Sets the nonce of this CommonMessageHeader.


        :param nonce: The nonce of this CommonMessageHeader.
        :type nonce: str
        """

        self._nonce = nonce

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this CommonMessageHeader.


        :return: The timestamp of this CommonMessageHeader.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this CommonMessageHeader.


        :param timestamp: The timestamp of this CommonMessageHeader.
        :type timestamp: str
        """

        self._timestamp = timestamp

    @property
    def version(self) -> int:
        """Gets the version of this CommonMessageHeader.


        :return: The version of this CommonMessageHeader.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version: int):
        """Sets the version of this CommonMessageHeader.


        :param version: The version of this CommonMessageHeader.
        :type version: int
        """

        self._version = version
