from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.utils import util


class CommonResponseCodeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    RESPONSE_CODE_UNKNOWN = 'RESPONSE_CODE_UNKNOWN'
    OK = 'OK'
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    UNAUTHENTICATED = 'UNAUTHENTICATED'
    PERMISSION_DENIED = 'PERMISSION_DENIED'
    NOT_FOUND = 'NOT_FOUND'
    ALREADY_EXISTS = 'ALREADY_EXISTS'
    LIMIT_EXCEEDED = 'LIMIT_EXCEEDED'
    UNAVAILABLE = 'UNAVAILABLE'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    NETWORK_ERROR = 'NETWORK_ERROR'
    INVALID_CERT = 'INVALID_CERT'
    NOT_SUPPORTED = 'NOT_SUPPORTED'
    DATA_CORRUPTED = 'DATA_CORRUPTED'
    def __init__(self):  # noqa: E501
        """CommonResponseCodeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CommonResponseCodeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The commonResponseCodeEnum of this CommonResponseCodeEnum.  # noqa: E501
        :rtype: CommonResponseCodeEnum
        """
        return util.deserialize_model(dikt, cls)
