from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.models.common_response_code_enum import CommonResponseCodeEnum
from backend.utils import util

from backend.models.common_response_code_enum import CommonResponseCodeEnum  # noqa: E501

class CommonResponseStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=CommonResponseCodeEnum.RESPONSE_CODE_UNKNOWN, message=None):  # noqa: E501
        """CommonResponseStatus - a model defined in OpenAPI

        :param code: The code of this CommonResponseStatus.  # noqa: E501
        :type code: CommonResponseCodeEnum
        :param message: The message of this CommonResponseStatus.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': CommonResponseCodeEnum,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'CommonResponseStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The commonResponseStatus of this CommonResponseStatus.  # noqa: E501
        :rtype: CommonResponseStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> CommonResponseCodeEnum:
        """Gets the code of this CommonResponseStatus.


        :return: The code of this CommonResponseStatus.
        :rtype: CommonResponseCodeEnum
        """
        return self._code

    @code.setter
    def code(self, code: CommonResponseCodeEnum):
        """Sets the code of this CommonResponseStatus.


        :param code: The code of this CommonResponseStatus.
        :type code: CommonResponseCodeEnum
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this CommonResponseStatus.


        :return: The message of this CommonResponseStatus.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this CommonResponseStatus.


        :param message: The message of this CommonResponseStatus.
        :type message: str
        """

        self._message = message
