from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend.models.base_model import Model
from backend.utils import util


class CommonAuthenticateTypeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AUTHENTICATE_TYPE_UNKNOWN = 'AUTHENTICATE_TYPE_UNKNOWN'
    AUTHENTICATE_TYPE_CERT = 'AUTHENTICATE_TYPE_CERT'
    AUTHENTICATE_TYPE_TOKEN = 'AUTHENTICATE_TYPE_TOKEN'
    def __init__(self):  # noqa: E501
        """CommonAuthenticateTypeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CommonAuthenticateTypeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The commonAuthenticateTypeEnum of this CommonAuthenticateTypeEnum.  # noqa: E501
        :rtype: CommonAuthenticateTypeEnum
        """
        return util.deserialize_model(dikt, cls)
